package cli

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

type Options struct {
	Version string
	Stdout  io.Writer
	Stderr  io.Writer
}

type App struct {
	version string
	stdout  io.Writer
	stderr  io.Writer
}

func New(opts Options) *App {
	if opts.Version == "" {
		opts.Version = "dev"
	}
	if opts.Stdout == nil {
		opts.Stdout = os.Stdout
	}
	if opts.Stderr == nil {
		opts.Stderr = os.Stderr
	}
	return &App{version: opts.Version, stdout: opts.Stdout, stderr: opts.Stderr}
}

func (a *App) Run(args []string) int {
	cmd := a.rootCommand()
	cmd.SetArgs(args)
	cmd.SetOut(a.stdout)
	cmd.SetErr(a.stderr)
	cmd.SilenceUsage = true
	cmd.SilenceErrors = true

	if err := cmd.Execute(); err != nil {
		fmt.Fprintln(a.stderr, err.Error())
		return 1
	}
	return 0
}

func (a *App) rootCommand() *cobra.Command {
	state := &globalState{}
	root := &cobra.Command{
		Use:     "cam",
		Short:   "Code Assistant Manager",
		Long:    "Code Assistant Manager (CAM) manages AI coding assistant configuration, prompts, skills, plugins, MCP servers, and launch commands.\n\nAliases: launch/l, doctor/d, agent/ag, prompt/p, skill/s, plugin/pl, mcp/m, upgrade/u, install/i, uninstall/un, config/cf, completion/comp/c, version/v.",
		Version: a.version,
	}
	root.SetVersionTemplate("{{.Version}}\n")
	root.PersistentFlags().StringVar(&state.configPath, "config", "", "Path to CAM config.yaml")
	root.PersistentFlags().StringVar(&state.providersPath, "providers", "", "Path to providers.json")
	root.PersistentFlags().StringVar(&state.storePath, "store", "", "Path to command state store")

	root.AddCommand(a.versionCommand())
	root.AddCommand(a.completionCommand())
	root.AddCommand(a.launchCommand(state))
	root.AddCommand(a.doctorCommand(state))
	root.AddCommand(a.configCommand(state))
	root.AddCommand(a.managementCommand("agent", "ag", state))
	root.AddCommand(a.managementCommand("prompt", "p", state))
	root.AddCommand(a.managementCommand("skill", "s", state))
	root.AddCommand(a.managementCommand("plugin", "pl", state))
	root.AddCommand(a.mcpCommand(state))
	root.AddCommand(a.lifecycleCommand("upgrade", "u"))
	root.AddCommand(a.lifecycleCommand("install", "i"))
	root.AddCommand(a.lifecycleCommand("uninstall", "un"))
	return root
}

type globalState struct {
	configPath    string
	providersPath string
	storePath     string
}

func (a *App) versionCommand() *cobra.Command {
	return &cobra.Command{
		Use:     "version",
		Aliases: []string{"v"},
		Short:   "Display current version",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			_, err := fmt.Fprintln(cmd.OutOrStdout(), a.version)
			return err
		},
	}
}

func (a *App) completionCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "completion [bash|zsh|fish|powershell]",
		Aliases: []string{"comp", "c"},
		Short:   "Generate shell completion scripts",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			shell := strings.ToLower(args[0])
			supported := map[string]bool{"bash": true, "zsh": true, "fish": true, "powershell": true}
			if !supported[shell] {
				return fmt.Errorf("Unsupported shell: %s", shell)
			}
			_, err := fmt.Fprintf(cmd.OutOrStdout(), "# code-agent-manager %s completion\n# Generated by CAM\n", shell)
			return err
		},
	}
	return cmd
}
